In [91]:
from pandas_datareader import data
import datetime
from bokeh.plotting import figure, show, output_file

start = datetime.datetime(2020,2,20)
end = datetime.datetime(2020,8,31)

df = data.DataReader(name = 'AMZN', data_source = 'yahoo', start = start, end = end)  

def inc_dec(c, o): 
    if c>0: 
        value = 'Increase'
    elif c<0: 
        value = 'Decrease'
    else: 
        value = 'Equal'
    return value 

df['Status'] = [inc_dec(c,o) for c,o in zip(df.Close,df.Open)]
df['Middle'] = (df.Open+df.Close)/2
df['Height'] = abs(df.Close-df.Open)

date_increase = df.index[df.Close > df.Open]
date_decrease = df.index[df.Close < df.Open]

p = figure(x_axis_type = 'datetime', width = 1000, height = 300)
# p.title = This is a chart
p.grid.grid_line_alpha = 0.3

hours_12 = 12*60*60*1000

p.segment(df.index, df.High, df.index, df.Low, color = 'blue')

p.rect(df.index[df.Status == 'Increase'], df.Middle[df.Status == "Increase"], 
       hours_12, df.Height[df.Status == 'Increase'], fill_color = 'green', line_color='black') 

p.rect(df.index[df.Status == 'Decrease'], df.Middle[df.Status == "Decrease"], 
       hours_12, df.Height[df.Status == 'Decrease'], fill_color = 'pink', line_color='black') 


output_file('Stock.html')
show(p)

In [92]:
df

,High,Low,Open,Close,Volume,Adj Close,Status,Middle,Height
Date,,,,,,,,,
2020-02-20,2176.790039,2127.449951,2173.070068,2153.100098,3131300,2153.100098,Increase,2163.085083,19.969971
2020-02-21,2144.550049,2088.000000,2142.149902,2095.969971,4646300,2095.969971,Increase,2119.059937,46.179932
2020-02-24,2039.300049,1987.969971,2003.180054,2009.290039,6547000,2009.290039,Increase,2006.235046,6.109985
2020-02-25,2034.599976,1958.420044,2026.420044,1972.739990,6219100,1972.739990,Increase,1999.580017,53.680054
2020-02-26,2014.670044,1960.449951,1970.280029,1979.589966,5224600,1979.589966,Increase,1974.934998,9.309937
...,...,...,...,...,...,...,...,...,...
2020-08-25,3357.399902,3267.000000,3294.989990,3346.489990,3992800,3346.489990,Increase,3320.739990,51.500000
2020-08-26,3451.739990,3344.570068,3351.110107,3441.850098,6508700,3441.850098,Increase,3396.480103,90.739990
2020-08-27,3453.000000,3378.000000,3450.050049,3400.000000,4264800,3400.000000,Increase,3425.025024,50.050049
2020-08-28,3433.370117,3386.500000,3423.000000,3401.800049,2894100,3401.800049,Increase,3412.400024,21.199951
2020-08-31,3495.000000,3405.000000,3408.989990,3450.959961,4025447,3450.959961,Increase,3429.974976,41.969971